### ISSUE TITLE
Fix problems with storybook

### ISSUE THREAD

**Issue by ItsPierre** [Crystal-Creations-GbR/crystal-components#39]
**Is your feature request related to a problem? Please describe.**
While trying to create stories for vue components, some problems occurred with the slot, v-model and absolute components like a snackbar.

**TODOs**

- [ ] How to implement an absolute component like the snackbar, which is not contained in the storybook div, but always tries to get the full window?
- [ ] How could we add a button to display absolute components like the snackbar?
- [ ] How to define slot values
- [ ] How to use v-model correctly (atm using `modelValue` which will not be updated)
- [ ] Add Buttons that show the snackbar

An example story of the snackbar component is pushed in this branch: https://github.com/Crystal-Creations-GbR/crystal-components/tree/story/snackbar-story

**Comment by ItsPierre** [comment]
I also get an error in my IDE for the import in the story: `Cannot find module ../src/components/CLicenseCard.vue or its corresponding type declarations`. Can you reproduce that @johannes-huther ?

**Comment by ItsPierre** [comment]
If this problems are solved, we can add stories for `CSnackbar`, `CSnackbarManager` and `CItemListGroup`.
